//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace T2.CLS.StorageService.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Logs {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Logs() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("T2.CLS.StorageService.Properties.Logs", typeof(Logs).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Start Create ODBC Connection.
        /// </summary>
        internal static string SML00001 {
            get {
                return ResourceManager.GetString("SML00001", resourceCulture);
            }
        }

        ///<summary>
        ///Open ODBC Connection
        ///</summary>
        internal static string SML00002
        {
            get
            {
                return ResourceManager.GetString("SML00002", resourceCulture);
            }
        }

        ///<summary>
        ///Create new Data Base
        ///</summary>
        internal static string SML00003
        {
            get
            {
                return ResourceManager.GetString("SML00003", resourceCulture);
            }
        }

        ///<summary>
        ///DataBase changed
        ///</summary>
        internal static string SML00004
        {
            get
            {
                return ResourceManager.GetString("SML00004", resourceCulture);
            }
        }

        ///<summary>
        ///Create Log SystemEntry
        ///</summary>
        internal static string SML00005
        {
            get
            {
                return ResourceManager.GetString("SML00005", resourceCulture);
            }
        }

        ///<summary>
        ///SQL>> {commandText}
        ///</summary>
        internal static string SML00006
        {
            get
            {
                return ResourceManager.GetString("SML00006", resourceCulture);
            }
        }

        ///<summary>
        ///Log system entry created. SystemName='{systemConfigurationName}', SystemId='{systemConfigurationId}'.
        ///</summary>
        internal static string SML00007
        {
            get
            {
                return ResourceManager.GetString("SML00007", resourceCulture);
            }
        }

        ///<summary>
        ///LogSystem entry creation failed. SystemName='{systemConfigurationName}', SystemId='{systemConfigurationId}'
        ///</summary>
        internal static string SML00008
        {
            get
            {
                return ResourceManager.GetString("SML00008", resourceCulture);
            }
        }

        ///<summary>
        ///Can not open connection. ConnectionString='{configurationConnectionString}'.
        ///</summary>
        internal static string SML00009
        {
            get
            {
                return ResourceManager.GetString("SML00009", resourceCulture);
            }
        }

        ///<summary>
        ///LogTable creation failed. SystemName='{logSystemName}', TableSchema:\n{tableSchema}
        ///</summary>
        internal static string SML00010
        {
            get
            {
                return ResourceManager.GetString("SML00010", resourceCulture);
            }
        }

        ///<summary>
        ///SQL>> {sqlQuery}
        ///</summary>
        internal static string SML00011
        {
            get
            {
                return ResourceManager.GetString("SML00011", resourceCulture);
            }
        }

        ///<summary>
        ///Log table entry created. SystemName='{systemName}', TableName='{tableName}'.
        ///</summary>
        internal static string SML00012
        {
            get
            {
                return ResourceManager.GetString("SML00012", resourceCulture);
            }
        }

        ///<summary>
        ///LogTable entry creation failed. SystemName='{systemName}', TableName='{tableName}'
        ///</summary>
        internal static string SML00013
        {
            get
            {
                return ResourceManager.GetString("SML00013", resourceCulture);
            }
        }

        ///<summary>
        ///Create Log Table Entry 
        ///</summary>
        internal static string SML00014
        {
            get
            {
                return ResourceManager.GetString("SML00014", resourceCulture);
            }
        }

        ///<summary>
        ///SQL>> {commandText}
        ///</summary>
        internal static string SML00015
        {
            get
            {
                return ResourceManager.GetString("SML00015", resourceCulture);
            }
        }

        ///<summary>
        ///Create Table
        ///</summary>
        internal static string SML00016
        {
            get
            {
                return ResourceManager.GetString("SML00016", resourceCulture);
            }
        }

        ///<summary>
        ///Table {tableName} created.
        ///</summary>
        internal static string SML00017
        {
            get
            {
                return ResourceManager.GetString("SML00017", resourceCulture);
            }
        }

        ///<summary>
        ///Table {tableName} creation failed.
        ///</summary>
        internal static string SML00018
        {
            get
            {
                return ResourceManager.GetString("SML00018", resourceCulture);
            }
        }

        ///<summary>
        ///Drop Table
        ///</summary>
        internal static string SML00019
        {
            get
            {
                return ResourceManager.GetString("SML00019", resourceCulture);
            }
        }

        ///<summary>
        ///SQL>> {commandText}
        ///</summary>
        internal static string SML00020
        {
            get
            {
                return ResourceManager.GetString("SML00020", resourceCulture);
            }
        }

        ///<summary>
        ///Ensure Log System
        ///</summary>
        internal static string SML00021
        {
            get
            {
                return ResourceManager.GetString("SML00021", resourceCulture);
            }
        }

        ///<summary>
        ///SQL>> {commandText}
        ///</summary>
        internal static string SML00022
        {
            get
            {
                return ResourceManager.GetString("SML00022", resourceCulture);
            }
        }

        ///<summary>
        ///Found System Configuration. Id: {systemConfigurationId}
        ///</summary>
        internal static string SML00023
        {
            get
            {
                return ResourceManager.GetString("SML00023", resourceCulture);
            }
        }

        ///<summary>
        ///LogSystem configuration failed. SystemName='{systemConfigurationName}'.
        ///</summary>
        internal static string SML00024
        {
            get
            {
                return ResourceManager.GetString("SML00024", resourceCulture);
            }
        }

        ///<summary>
        ///Find Table
        ///</summary>
        internal static string SML00025
        {
            get
            {
                return ResourceManager.GetString("SML00025", resourceCulture);
            }
        }

        ///<summary>
        ///SQL>> {commandText}
        ///</summary>
        internal static string SML00026
        {
            get
            {
                return ResourceManager.GetString("SML00026", resourceCulture);
            }
        }

        ///<summary>
        ///Existing table '{tableName}' found.
        ///</summary>
        internal static string SML00027
        {
            get
            {
                return ResourceManager.GetString("SML00027", resourceCulture);
            }
        }

        ///<summary>
        ///Get Log Tables
        ///</summary>
        internal static string SML00028
        {
            get
            {
                return ResourceManager.GetString("SML00028", resourceCulture);
            }
        }

        ///<summary>
        ///SQL>> {commandText}
        ///</summary>
        internal static string SML00029
        {
            get
            {
                return ResourceManager.GetString("SML00029", resourceCulture);
            }
        }

        ///<summary>
        ///Get Log Tables By System Name
        ///</summary>
        internal static string SML00030
        {
            get
            {
                return ResourceManager.GetString("SML00030", resourceCulture);
            }
        }

        ///<summary>
        ///SQL>> {commandText}
        ///</summary>
        internal static string SML00031
        {
            get
            {
                return ResourceManager.GetString("SML00031", resourceCulture);
            }
        }

        ///<summary>
        ///InitStorage
        ///</summary>
        internal static string SML00032
        {
            get
            {
                return ResourceManager.GetString("SML00032", resourceCulture);
            }
        }

        ///<summary>
        ///SQL>> {commandText}
        ///</summary>
        internal static string SML00033
        {
            get
            {
                return ResourceManager.GetString("SML00033", resourceCulture);
            }
        }

        ///<summary>
        ///SQL>> {commandText}
        ///</summary>
        internal static string SML00034
        {
            get
            {
                return ResourceManager.GetString("SML00034", resourceCulture);
            }
        }

        ///<summary>
        ///SQL>> {commandText}
        ///</summary>
        internal static string SML00035
        {
            get
            {
                return ResourceManager.GetString("SML00035", resourceCulture);
            }
        }

        ///<summary>
        ///SQL>> {commandText}
        ///</summary>
        internal static string SML00036
        {
            get
            {
                return ResourceManager.GetString("SML00036", resourceCulture);
            }
        }

        ///<summary>
        ///Error Init storage
        ///</summary>
        internal static string SML00037
        {
            get
            {
                return ResourceManager.GetString("SML00037", resourceCulture);
            }
        }

        ///<summary>
        ///Is Log Table
        ///</summary>
        internal static string SML00038
        {
            get
            {
                return ResourceManager.GetString("SML00038", resourceCulture);
            }
        }

        ///<summary>
        ///SQL>> {commandText}
        ///</summary>
        internal static string SML00039
        {
            get
            {
                return ResourceManager.GetString("SML00039", resourceCulture);
            }
        }

        ///<summary>
        ///'{TableName}' is log table: {isLog}
        ///</summary>
        internal static string SML00040
        {
            get
            {
                return ResourceManager.GetString("SML00040", resourceCulture);
            }
        }

        ///<summary>
        ///Rename Log Table
        ///</summary>
        internal static string SML00041
        {
            get
            {
                return ResourceManager.GetString("SML00041", resourceCulture);
            }
        }

        ///<summary>
        ///SQL>> {commandText}
        ///</summary>
        internal static string SML00042
        {
            get
            {
                return ResourceManager.GetString("SML00042", resourceCulture);
            }
        }

        ///<summary>
        ///LogTable entry updated. Old TableName='{oldTableName}', new TableName='{newTableName}'.
        ///</summary>
        internal static string SML00043
        {
            get
            {
                return ResourceManager.GetString("SML00043", resourceCulture);
            }
        }

        ///<summary>
        ///Renaming LogTable failed. Old TableName='{oldTableName}', new TableName='{newTableName}'.
        ///</summary>
        internal static string SML00044
        {
            get
            {
                return ResourceManager.GetString("SML00044", resourceCulture);
            }
        }

        ///<summary>
        ///Rename Table
        ///</summary>
        internal static string SML00045
        {
            get
            {
                return ResourceManager.GetString("SML00045", resourceCulture);
            }
        }

        ///<summary>
        ///SQL>> {commandText}
        ///</summary>
        internal static string SML00046
        {
            get
            {
                return ResourceManager.GetString("SML00046", resourceCulture);
            }
        }

        ///<summary>
        ///Table '{oldTableName}' renamed to '{newTableName}'.
        ///</summary>
        internal static string SML00047
        {
            get
            {
                return ResourceManager.GetString("SML00047", resourceCulture);
            }
        }

        ///<summary>
        ///Renaming table failed. Old TableName='{oldTableName}', new TableName='{newTableName}'.
        ///</summary>
        internal static string SML00048
        {
            get
            {
                return ResourceManager.GetString("SML00048", resourceCulture);
            }
        }

        ///<summary>
        ///Update Log Table
        ///</summary>
        internal static string SML00049
        {
            get
            {
                return ResourceManager.GetString("SML00049", resourceCulture);
            }
        }

        ///<summary>
        ///Updating LogTable failed. SystemName='{systemConfigurationName}'.
        ///</summary>
        internal static string SML00050
        {
            get
            {
                return ResourceManager.GetString("SML00050", resourceCulture);
            }
        }


    }
}
